version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: occount_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: occount
      POSTGRES_PASSWORD: occount1234
      POSTGRES_DB: occount_db
    ports:
      - "5432:5432"
    volumes:
      - occount_pg_data:/var/lib/postgresql/data

volumes:
  occount_pg_data:
